apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-3-helm.fullname" . }}
  labels:
    {{- include "app-3-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-3-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        {{- include "app-3-helm.selectorLabels" . | nindent 8 }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
      serviceAccountName: {{ include "app-3-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_CONFIG_NAME
              value: application,routes
            - name: SPRING_CONFIG_LOCATION
              value: file:///deployments/config/
            - name: SPRING_PROFILES_ACTIVE
              value: application,routes
          volumeMounts:
            - name: application-config
              mountPath: "/deployments/config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 10              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: application-config
          configMap:
            name: {{ include "app-3-helm.fullname" . }}
            items:
            - key: application-routes.yml
              path: application-routes.yml
